---

- name: "Check if Vagrant is installed"
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1

- name: "Download Vagrant {{ vagrant.version }}"
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/vagrant_{{ vagrant.version }}_x86_64.deb"
    dest: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1

- name: "Install Vagrant {{ vagrant.version }}"
  apt:
    deb: "/tmp/download-vagrant-latest.deb"
  when: vagrant_check_deb.rc == 1
  become: true

- name: "Install Vagrant plugins"
  command: "vagrant plugin install {{ item }}"
  with_items:
#    - vagrant-cachier
#    - vagrant-gatling-rsync
#    - vagrant-share
#    - vagrant-hostsupdater
#    - vagrant-hostmanager
#    - vagrant-triggers
    - vagrant-vbguest
#    - vagrant-bindfs
#    - vagrant-lxc
  become: true

# TODO: Research viability in project
#- name: Install nfs (nfs-kernel-server)
#  apt:
#    name: nfs-kernel-server
#  sudo: yes

- name: "Clean Vagrant deb file"
  file:
    path: /tmp/download-vagrant-latest.deb
    state: absent
