--- # TODO define locales further (and test them)

- name: "Allow apt to install packages from repositories using HTTPS"
  apt:
    pkg: apt-transport-https
    state: latest
    update_cache: true
  tags: always
  become: true

- name: "Configure locales"
  lineinfile: dest=/var/lib/locales/supported.d/local regexp="{{ item }}" line="{{ item }}" create="yes"
  notify:
    - generate-locales
  with_items: "{{ locales }}"
  tags: locale

- name: "Set localtime (/etc/localtime)"
  copy: remote_src=yes src="/usr/share/zoneinfo/{{ timezone }}" dest=/etc/localtime
  tags: timezone

- name: "Set timezone (/etc/timezone)"
  copy: content="{{ timezone }}\n" dest=/etc/timezone
  notify:
    - update-timezone
  tags: timezone

- name: "Install ntp package"
  action: apt pkg=ntp state=latest update_cache=yes cache_valid_time="{{ aptcachetime }}"
  tags: timezone
